### ISSUE TITLE
Uploading 1e character when selecting v2 does not work.

### ISSUE THREAD

**Issue by PSCourtney** [BrightsDays/pocket-cairn#35]
As above, when selecting 2e and uploading a 1e character it just auto selects 1e.

Is this intended? 

Thanks in advance.

**Comment by BrightsDays** [comment]
Hi!
Yes, it intended - but I will think about conversation methods on this week, looks like we easily can use 1st edition character in second one.

**Comment by BrightsDays** [comment]
I have added a conversion method (1ed to 2ed) to the main page.

**Comment by PSCourtney** [comment]
that's great work, thank you!
